--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MintoD/libMCUnicodeChars
build-by-default: true
branches:
- main
projects:
  libMCUnicodeChars:
    path: ""
    model: virion
    type: library
...
